env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  mocha: true
extends: plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  'no-unused-vars': ['error', {argsIgnorePattern: 'next'}]
}
