name: Production Deploy
on:
    push:
        branches:
            - main
jobs:
    deplay-test-server:
        runs-on: ubuntu-latest
        steps:
            - name: Print branch name
              run: "echo Now deploying branch: $GITHUB_REF_NAME to production server"